name: "Usage question"
description: Questions related to the usage
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!

        Please, before submitting, make sure that:

        - You have checked the documentation and haven't found enough information
        - There is not an [existing issue](https://github.com/10kpw/TiingoJulia/issues) with the same question

        - You have read the [contributing guide](docs/src/90-contributing.md)


        - You are following the [code of conduct](https://github.com/10kpw/TiingoJulia/blob/main/CODE_OF_CONDUCT.md)


        The form below should help you in filling out this issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write your question
    validations:
      required: true
