name: Reusable test

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: "1"
      os:
        type: string
        default: ubuntu-latest
      arch:
        type: string
        default: x64
      allow_failure:
        type: boolean
        default: false
      run_codecov:
        type: boolean
        default: false
    secrets:
      codecov_token:
        required: true

jobs:
  test:
    name: Julia ${{ inputs.version }} - ${{ inputs.os }} - ${{ inputs.arch }} - ${{ github.event_name }}
    runs-on: ${{ inputs.os }}
    continue-on-error: ${{ inputs.allow_failure }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ inputs.version }}
          arch: ${{ inputs.arch }}

      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Process coverage
        if: ${{ inputs.run_codecov }}
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage to Codecov
        if: ${{ inputs.run_codecov }}
        uses: codecov/codecov-action@v5
        with:
          file: lcov.info
          token: ${{ secrets.codecov_token }}
