name: Test

on:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ReusableTest.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, version: "1", arch: x64, run_codecov: true}
          - {os: ubuntu-latest, version: "lts", arch: x64}
          - {os: macOS-latest, version: "1", arch: x64}
          - {os: macOS-latest, version: "lts", arch: x64}
          - {os: windows-latest, version: "1.9", arch: x64}
          - {os: windows-latest, version: "lts", arch: x64}
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      run_codecov: ${{ matrix.run_codecov || false }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
